# Generated by Django 2.1 on 2018-08-19 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_userdetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Books',
        ),
    ]
