# Generated by Django 2.1 on 2018-08-19 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_auto_20180819_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookUserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portal.Book')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portal.UserDetails')),
            ],
        ),
    ]
